source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZJTools_Example', :exclusive => true do
  pod 'ZJTools', :path => '../'
end

target 'ZJTools_Tests', :exclusive => true do
  pod 'ZJTools', :path => '../'

  
end
